[package]
name = "game_2048"
version = "0.1.0"
authors = ["Nikita Goncharov <goncharovnikita.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
rand = "0.8.3"
